version: '3.9'

services:
  db:
    image: postgres
    container_name: movie-catalogue-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie-catalogue-api
    volumes:
      - pgdata:/data/postgres
    ports:
      - '5432:5432'

  app:
    build: .
    command: sh -c "npm run start:dev"
    container_name: movie-catalogue-api
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local