version: '3.9'

services:
  db:
    image: postgres
    container_name: movie-catalogue-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie-catalogue-api
    volumes:
      - pgdata:/data/postgres
    ports:
      - '5432:5432'
  
  redis:
    container_name: movie-catalogue-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  app:
    build: .
    command: sh -c "npm run migration:run; npm run start:dev"
    container_name: movie-catalogue-api
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
  redis:
    driver: local